### ISSUE TITLE
create curl bash install script

### ISSUE THREAD

**Issue by synedra** [rsds143/astra-cli#18]
With home-brew does the executable really go into ./bin?

Most people will have no idea which release they need.  Please make a Mac/Linux/Win executable.  On first run it should:

- Install the binary into the path or add the binary path to the PATH
- Run astra-setup, which guides you to get a token (which currently just populates .astrarc and .env but could pull the bundle)

**Comment by rsds143** [comment]
so homebrew is hugely popular and is on the "how to install" section for a number of similar tools including the official gihub cli, helm, k3d, etc.  

I did make executables for all the platforms are they are in the releases section of the website. I would think being able to download the latest would be fine. 
<img width="1267" alt="Capture d’écran 2021-09-28 à 14 54 33" src="https://user-images.githubusercontent.com/43972/135091158-963681be-9cef-4e6d-b73f-73bdd92c55d4.png">

I am sorry I just do not agree with the critique here apologies.

**Comment by rsds143** [comment]
how about we do the following:

- shell installer script (curl/wget)
- scoop or chocolatey (popular windows installer)

**Comment by foundev** [comment]
actually this is done in https://github.com/rsds143/astra-cli/pull/29
