### ISSUE TITLE
Polish up command calls

### ISSUE THREAD

**Issue by synedra** [rsds143/astra-cli#19]
We should never have ./bin/whatever.  It is fragile (doesn't work everywhere) and looks immature.

We should get and put the bundle in a specific place (maybe ~/.config/astra/bundle?) or use the .astrarc/.env file

It should be called "astra" not "astra-cli" to match with other cli's out there.

**Comment by rsds143** [comment]
* I don't agree about ./bin being immature, I can link a bunch of other projects using that in their docs (and have over decades), but I think we can do other things with our time, it doesn't bother me to remove it from the docs in any case
* calling it astra I would just like some coordination with anyone else making similar tools
* so the idea with the bundle is you would need it for an app, I have to suggest dropping it into a ~/.config folder strikes me as hugely surprising

**Comment by rsds143** [comment]
* removed bin in docs #28 
* changed cli name #27 

I hope those two will satisfy the overall goal enough, you're welcome to reopen if you do not agree and we can discuss it further
